version: '3.4'

services:
  rendafixa:
    image: rendafixa
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5002"]
    ports:
      - 5002:5002
      - 5678:5678
    environment:
      - FLASK_APP=app.py
      - MONGODB_HOST=mongodb://root:root@mongo:27017/
    depends_on:
      - mongo
  mongo:
    image: mongo:7-jammy
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root