swagger: "2.0"
parameters:
  - name: name
    in: query
    type: string
    required: true
    description: Name of the simulation
  - name: months_invested
    in: query
    type: integer
    required: true
    description: Time in months in which the money will be invested
  - name: initial_value
    in: query
    type: number
    required: true
    description: Initial value of the application
  - name: monthly_investment
    in: query
    type: number
    required: true
    description: Amount invested each month
  - name: monthly_interest_rate
    in: query
    type: number
    required: true
    description: Percentage earned each month
  - name: compensation
    in: query
    type: string
    enum:
      - "pre-fixed"
      - "post-fixed"
    required: true
    description: Type of compensation
responses:
  201:
    description: Simulation created
    schema:
      properties:
        final_amount:
          type: number
          description: Total value after months
        total_invested:
          type: number
          description: Total value invested after months
        total_interest:
          type: number
          description: Profit received
  400:
    description: Invalid request
